### ISSUE TITLE
Responsive Site and Mobile First

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/phalcon.io#7]
Hi we have a big problem with responsive in the site

```css
body {
    background: #fff;
    color: #000000;
    font: 16px/24px Ubuntu, sans-serif;
    min-width: 990px; /* very wrong */
}
```
[source](https://github.com/phalcon/website/blob/master/public/css/style.css#L11)
